name: Manual Trigger (no commit)

on:
  workflow_dispatch:
    inputs:

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm start
        env:
          MODE: manual
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          DATABASE_ID_BACKLOG: ${{ secrets.DATABASE_ID_BACKLOG }}
          DATABASE_ID_SPRINT_SUMMARY: ${{ secrets.DATABASE_ID_SPRINT_SUMMARY }}
          DATABASE_ID_DAILY_SUMMARY: ${{ secrets.DATABASE_ID_DAILY_SUMMARY }}
          BACKLOG_PROPERTY_SPRINT: Sprint
          BACKLOG_PROPERTY_EXCLUDE_STATUS_PATTERN: Ready to Deploy|DONE*
          BACKLOG_PROPERTY_STORY_POINTS: Story Estimate
